
replicaCount: 3

image:
  repository: "gcr.io/k8s-proj-439420/tasky-image"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

serviceAccount:
  create: true
  name: tasky-service-account

mongodb:
  uri: ""
  
ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
