replicaCount: 3

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

serviceAccount:
  create: true
  name: tasky-service-account

mongodb:
  uri: ""

ingress:
  enabled: true
  hosts:
    - host: "<dynamically set IP here>"
      paths:
        - path: /
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
