replicaCount: 1

image:
  repository: tasky
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  MONGODB_URI: "mongodb://mongo-service:27017/taskydb"
  SECRET_KEY: "your_secret_key"

resources: {}
