apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: gcr.io/YOUR_GCP_PROJECT_ID/tasky-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-uri
