{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tasky-chart.fullname" . }}
  annotations:
    spec.ingressClassName: gce
spec:
  rules:
    - host: bradleysproject.duckdns.org
      http:
        paths:
          - path: /assets/css/
            pathType: Prefix
            backend:
              service:
                name: {{ include "tasky-chart.fullname" . }}
                port:
                  number: 8080
          - path: /assets/js/
            pathType: Prefix
            backend:
              service:
                name: {{ include "tasky-chart.fullname" . }}
                port:
                  number: 8080
          - path: /signup
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "tasky-chart.fullname" . }}
                port:
                  number: 8080                  
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "tasky-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  defaultBackend:
    service:
      name: {{ include "tasky-chart.fullname" . }}
      port:
        number: {{ .Values.service.port }}
{{- end }}
