apiVersion: v1
kind: Service
metadata:
  name: {{ include "tasky-chart.fullname" . }}
  labels:
    {{- include "tasky-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: 32080  # Specify a static NodePort (optional, or use an automatically assigned port)
  selector:
    {{- include "tasky-chart.selectorLabels" . | nindent 4 }}
