apiVersion: v1
kind: Service
metadata:
  name: {{ include "tasky-chart.fullname" . }}
  labels:
    {{- include "tasky-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}  # Use the type specified in values.yaml
  ports:
    - port: {{ .Values.service.port }}  # Use the port specified in values.yaml
      targetPort: http                   # Change to the appropriate target port if necessary
      protocol: TCP
      name: http
  selector:
    {{- include "tasky-chart.selectorLabels" . | nindent 4 }}
