apiVersion: v1
kind: Service
metadata:
  name: {{ include "tasky-chart.fullname" . }}
  labels:
    {{- include "tasky-chart.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}' 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "tasky-chart.selectorLabels" . | nindent 4 }}
