name: Application Deploy

on:
  push:
    branches:
      - main
    paths:
      - "app/**"  # Trigger on changes to the app directory
      - ".github/workflows/app-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}


    - name: Deploy Application with Helm
      run: |
        helm upgrade --install tasky ./app/tasky-chart \
          --namespace default \
          --set image.repository=gcr.io/${{ secrets.GCP_PROJECT_ID }}/tasky-image \
          --set image.tag=${{ github.sha }} \
          --set mongodb.uri=mongodb://${{ secrets.MONGO_IP }}:27017 \
          --wait
