name: Deploy Project with IaC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}


    #   # Terraform refresh
    # - name: Terraform refresh
    #   run: terraform refresh

    # Terraform Init and Apply (Provision GKE and Infrastructure)
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve 
      env:
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}


   # Configure kubectl to use GKE cluster credentials
    - name: Authenticate with GKE
      run: |
        echo "${{ secrets.CI_CD_PIPELINE_SERVICE_KEY }}" > sa-key.json
        gcloud auth activate-service-account --key-file=sa-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}

    # Apply Kubernetes manifests (Deployment and Service)
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml


      # Clean up the JSON file after use for security
    - name: Clean up
      run: rm sa-key.json
