name: Deploy Project with IaC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

      # Create the Service Account Key File
    - name: Create sa-key.json for Authentication
      run: echo "${{ secrets.GCP_SA_KEY }}" > sa-key.json

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Terraform Init (Provision GKE and Infrastructure)
    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: sa-key.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}

    # Import Existing GKE Cluster
    - name: Import Existing GKE Cluster
      run: terraform import google_container_cluster.primary projects/${{ secrets.GCP_PROJECT_ID }}/locations/${{ secrets.GKE_CLUSTER_ZONE }}/clusters/${{ secrets.GKE_CLUSTER_NAME }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: sa-key.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}


    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve 
      env:
        GOOGLE_APPLICATION_CREDENTIALS: sa-key.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}


   # Configure kubectl to use GKE cluster credentials
    - name: Authenticate with GKE
      run: |
        echo "${{ secrets.CI_CD_PIPELINE_SERVICE_KEY }}" > sa-key.json
        gcloud auth activate-service-account --key-file=sa-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}

    # Apply Kubernetes manifests (Deployment and Service)
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml


      # Clean up the JSON file after use for security
    - name: Clean up
      run: rm sa-key.json
